### PR TITLE
Add missing pictureClassName & pictureStyle

### PR DESCRIPTION
**Pull request by robrechtme**
The `pictureClassName` and `pictureStyle` prop are only passed to the sizer and the `<noscript>` part. I'm guessing this is a mistake? Shouldn't the actual `<picture>` tag take the props? 🙂

### CODE REVIEW

**Comment by dbismut** [comment]
Unfortunately I think there are several things that are broken in the way styles or classes are applied, that go beyond this PR. The `picture` element shouldn't be styled, only the inner `img` as picture. In fact, without using descendent selectors it is impossible to style the height of the image.

Also not sure if I'm having troubles with the repo config but tests always fail and I have plenty of typescript errors.

**Comment by robrechtme** [comment]
You're right. I should've tested this first. I suggest we move all the styles applied to the `picture` element to the `img` tag? I tried this and then it is also possible to style the height (e.g. `width: 'auto', height: '100%'` ). 

Regarding the tests, I think the snapshot tests are outdated. I don't have TS errors though.

**Comment by dbismut** [comment]
Hi @robrechtme sorry if this came as if I was blaming you, I wasn't. Tests fail me on the original repo so I was more blaming the tests. Do you manage to build the lib running `yarn build`? This is where I'm confronted with hundreds of errors.

Anyway I ended up using `next/image` component...

**Comment by stefanoverna** [comment]
Hey guys!
1. Tests seem to work fine, so should be something on your end! -> https://travis-ci.org/github/datocms/react-datocms
2. You're right @dbismut, className/style should not be applied to <picture />  but on the inner . We fixed this in the latest version! b8e4c9360aa768f0d03

@robrechtme the idea of the picture element is that that it simply provides source information for its enclosed img element, and that it is always the img element that is rendered, not the picture element.

I'm gonna close this for now, but feel free to reopen if needed!

**Comment by robrechtme** [comment]
@stefanoverna thanks! That's exactly what I meant to do. One question, shouldn't the major version be increased, as this is a breaking change?

**Comment by stefanoverna** [comment]
the final effect on the rendering page should not change, so to me its minor.. but I could be wrong? :/

**Comment by dbismut** [comment]
Well that depends @stefanoverna. 

If users passed a class with the intention of targeting the img component (with the intent of fixing what this PR resolves), something such as:

```css
.myPictureClass > img {
  height: 100%;
}
```

That would no longer work when applied directly to the img tag and indeed break.

**Pull request closed without merging**
